// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCMafKT8CVT9e1AgParwIx8Ds3RfuWIFA',
    appId: '1:334307797736:web:168358d6d26a188509375d',
    messagingSenderId: '334307797736',
    projectId: 'my-app-sakani',
    authDomain: 'my-app-sakani.firebaseapp.com',
    storageBucket: 'my-app-sakani.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbo4mVyqYfBy9S0pM5_PUu3U4f3gjHYcw',
    appId: '1:334307797736:android:e28e93fdfe63d9e909375d',
    messagingSenderId: '334307797736',
    projectId: 'my-app-sakani',
    storageBucket: 'my-app-sakani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMXVBErhCgg7dGQNWYR086nuuWwRKzB6c',
    appId: '1:334307797736:ios:13f0f5b4b9c7338309375d',
    messagingSenderId: '334307797736',
    projectId: 'my-app-sakani',
    storageBucket: 'my-app-sakani.firebasestorage.app',
    iosBundleId: 'com.example.apartmentRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMXVBErhCgg7dGQNWYR086nuuWwRKzB6c',
    appId: '1:334307797736:ios:13f0f5b4b9c7338309375d',
    messagingSenderId: '334307797736',
    projectId: 'my-app-sakani',
    storageBucket: 'my-app-sakani.firebasestorage.app',
    iosBundleId: 'com.example.apartmentRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCMafKT8CVT9e1AgParwIx8Ds3RfuWIFA',
    appId: '1:334307797736:web:4fef616668bbc2ac09375d',
    messagingSenderId: '334307797736',
    projectId: 'my-app-sakani',
    authDomain: 'my-app-sakani.firebaseapp.com',
    storageBucket: 'my-app-sakani.firebasestorage.app',
  );
}
